language: python
sudo: required
python: 3.5
services:
- docker
env:
- TOXENV=py27
- TOXENV=py35
install:
- pip install -U tox
script:
- tox
BROWSERSTACK_ACCESS_KEY:
  secure: p4EXh3s/+QyTUOWGaokLh88VKZ7HAs2GOK9GKsl3vPaYr6aTaCqBUbA893tcr+zyx5t6tWequUo3wS/5zWA9QXnMx2OLrU7x1XYArsw4JKvJVD5adQP0/tYlIiqqi0fr4QApmsFXYFWKohbbxV/hDgE83LSPGijJYaUENwA0N6IPYWg5fstyEbMsBViIYeF/fsvieXyLuXnq6Rn4kIMtryXoqQRStT1veyHBcrUxj33Z2jRjPl/HCy+GYJRh9MKLiIIA/cMTR3+1AphrFdNFOFrfGMjsLQwuVoV8Ej4foNvWmG7SW/jAGpL+jnfegVQINhJWH08aDnsh6g9lmYLuMCSmkCXUXUunu6CHxvTVDswiqVmkwUZk5QyA69+n4EdWezBz+kX6s799A5dh0yD0TTzfe3IaGI+MIxAcfhpYFwAOeUdqPCfMOF5nmymcHAJzNx4Ru4VFw4yRSN1a8MxQ5FebMVdudp6ByWg4LNbEJ+Lj7+2jKfIRww9cheO6jOWlOMNioJu/0FIqLYxLAFbpaKoWfiHqyrjBEYAtWEcT5wRWKjQjPYGN9oidSg/F+DEIdCxy1j6hpdyRewl7GnJM/mrf+m3RLhJ+Z3HWsZ5B1AhYZ6BDMmypV60exu/HMWDiV5WSuWkUf4dB5P6wI+GPS+FvY9Dxgw5YY8vd6JcIdUQ=
