language: python
sudo: required
python: 3.5
services:
- docker
env:
  matrix:
  - TOXENV=py27
  - TOXENV=py35
  global:
    BROWSERSTACK_ACCESS_KEY:
      secure: Qroldws5YkHPyz7/UmHda+1ZZIIp4qYPLUnncEyVa5I6jlYFvp9htHelBFCZvN6JLw6+19080RFZ4lV2379COMOOSiF4Z1GYAO4zpid/aRAGBvyF/8Xoq+yYOVrf3R2l8IdmDur5HWzOPYFmwSLYIgPhvIUxNoInr0jyC3hmemFLNNjJlCkhyvXr4WM0EENDoufrAwJEY3Q95Bqb86s0klphvWDWjCfa10RcrqLYiHNoEBRELNZXgch5VcBRx3dey1VdR5Bu2x0fJHpwB42ui2LbwVhe+Wz0ObOzBhQ/5nHwBvVMgjy2BANzqOv+ri/fPfpkPBKvoPIzGpPByk4zoaRdyyu799OJ3laE213JkcF7Hg7tJKKtR+jW36H0A3JF4Ju1vwFZBhI4w4V47P21kexiv5Gb7j+ehMuVUSBWHBJgEUItP5UUFf3U/6u4FJ4McqJts+RjbQqPpnCn6gx7sGKxaZtkPL4NYhd+DbsI4cSTLOHZ698hIXTxPQqOrBybNSA1YdfTRSpXFLI9DKO3ctT9xuDjsIrlxBAIJaQc0VvBqJYIlGfn6vFybD/gDXL3IkUPWN36WBFfibKXL5/8RRrkytfUft4CAur2oIIgz5nUcaw001QFwrPtJpxDrsycHTSFTEkBhjrXaB0BJx9nvvxcwnFqaSVYLb8DjvVEa6Y=
    PIPPO1:
      secure: U/az7jw+V9ymJORso5Z6UwDNJqSme2AbmBQBi4DKSxMdYlBxtAzBCEpTa9kqY64dEX4GKEL7cGRmIvJk+UGeA23PQYHfTPA6vpTGhRpahFgR0YeS3vgwlqIaWOKaNpGX4A7/yU73Y/NR/46WDr+UIb6MYeWQ9FXOGGVDrvJFUrlav23RzrSHs9p4p4nMU+j13Mkl0/I6ibhINQiOu90WD5PBR3g6MjP5MJpa5bX0TBDIekQPUWBV/PS2XCrp9wIrZASlTK6Lpi7/BGiKgXkbSOCk1teLjdDFNap0iLxU/Cd1H4hxqn0K06p1xjkCVbKOzwlgppdF25OykQBpgUJihAHspIzo4SS5tdEYVMJ6AnkyjLVHlsFwhi5tO6xu3zVM0hmiOOQmQy9dlS0hnLdplmJVg5XyzrbN7CzB9YX+KHBdwuSUbqzzzsdPzfNMelewDpTGyJEu/l09cp3Fn3kQVMXyYQ5AGEiq6Qy2HLZdYzFMSxuQ1xBdkq5P3PNriKCne4GERoJ0zuPq2xk/0vWbLgHAKZfKSM5Fvir/wVdOHx8eyW3cA6AnuJImhs0KjTasDs+jXAdJp2wG8fbpjVyjKxcxD+x8fSoMOwt7ds8Dez1q3THMpT/vmg8PG7Ur6ViF/uRMmUiPqaafeKaIvKZDnwv48umuGLUvBGk43XW3nlo=
    PIPPO:
      secure: U/az7jw+V9ymJORso5Z6UwDNJqSme2AbmBQBi4DKSxMdYlBxtAzBCEpTa9kqY64dEX4GKEL7cGRmIvJk+UGeA23PQYHfTPA6vpTGhRpahFgR0YeS3vgwlqIaWOKaNpGX4A7/yU73Y/NR/46WDr+UIb6MYeWQ9FXOGGVDrvJFUrlav23RzrSHs9p4p4nMU+j13Mkl0/I6ibhINQiOu90WD5PBR3g6MjP5MJpa5bX0TBDIekQPUWBV/PS2XCrp9wIrZASlTK6Lpi7/BGiKgXkbSOCk1teLjdDFNap0iLxU/Cd1H4hxqn0K06p1xjkCVbKOzwlgppdF25OykQBpgUJihAHspIzo4SS5tdEYVMJ6AnkyjLVHlsFwhi5tO6xu3zVM0hmiOOQmQy9dlS0hnLdplmJVg5XyzrbN7CzB9YX+KHBdwuSUbqzzzsdPzfNMelewDpTGyJEu/l09cp3Fn3kQVMXyYQ5AGEiq6Qy2HLZdYzFMSxuQ1xBdkq5P3PNriKCne4GERoJ0zuPq2xk/0vWbLgHAKZfKSM5Fvir/wVdOHx8eyW3cA6AnuJImhs0KjTasDs+jXAdJp2wG8fbpjVyjKxcxD+x8fSoMOwt7ds8Dez1q3THMpT/vmg8PG7Ur6ViF/uRMmUiPqaafeKaIvKZDnwv48umuGLUvBGk43XW3nlo=
install:
- echo $PIPPO
- echo $PIPPO1
- pip install -U tox
script:
- tox

